### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by wumiton** [zy-sdn/onos-p4sr#1]
你好，
1.这边的p4src是否就是https://github.com/p4lang/switch/tree/master/p4src ?
2.如果将生成的oar安装到ONOS，激活以后，应该怎么使用？
3.这个是模仿onos/pipelines目录下的pipeconf写的吗？

**Comment by zy-sdn** [comment]
Hello，
1. 这个P4SRC是我们自己写的segment routing P4程序
2. 目前的代码只是课程作业的demo，还需要搭建一个简单的网络环境。然后在onos的控制台用p4sr命令可以实现基于段路由的服务链
3. 不是的，这个是模仿着bmv2-demo写的

**Comment by wumiton** [comment]
首先，谢谢。
1.我试图加入ONOS ，利用mvn install。发现这个版本是支持1.8的快照，我只是改成1.13的应该没什么影响吧？
2.只看到sr.json,方便的话，可以提供P4源码吗？方便做一些对照。谢谢。

**Comment by zy-sdn** [comment]
1. 不太确定ONOS 1.13是否还支持BMv2的Thrift接口以及相关驱动API，ONOS 1.11之后应该就只支持P4Runtime相关的接口，所以可能会有影响。
2. https://github.com/zy-sdn/onos-p4-dev/blob/master/p4src/sr.p4

**Comment by wumiton** [comment]
好的，谢谢。
